### ISSUE TITLE
用户中心是否应该添加一个菜单项 “My picture”

### ISSUE THREAD

**Issue by Joozo** [get3w/docs.get3w.com#7]
第一，用户可以统一管理上传了的照片。
第二，有一些区块，图片只能通过个性CSS来实现，而这个时候，在编辑器中是没有地儿可心上传图片的。亦或是很难找到上传位置的。
第三，如果添加这个菜单需要考虑两点，一是批量添加，二是添加后的图片对应会有一个绝对地址，可供复制，用户点击可以直接粘贴至对应的CSS属性中。

**Comment by starlying** [comment]
还没想好怎么实现，先放一下
